// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMvIAFaNPk9PHRpUc_LGiXkIF-kssbF8',
    appId: '1:714095999630:web:a81db7fb7d18fcecb427df',
    messagingSenderId: '714095999630',
    projectId: 'noteworthy-79a91',
    authDomain: 'noteworthy-79a91.firebaseapp.com',
    storageBucket: 'noteworthy-79a91.appspot.com',
    measurementId: 'G-5SHSEKJXWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvdN3stXDRqN88SCIB5Uf53ZJHTvFFXMQ',
    appId: '1:714095999630:android:978b336e6ce61d5ab427df',
    messagingSenderId: '714095999630',
    projectId: 'noteworthy-79a91',
    storageBucket: 'noteworthy-79a91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-tpw618a08X6lJZvha19J2kbLUMx-HE',
    appId: '1:714095999630:ios:c38450efc6154079b427df',
    messagingSenderId: '714095999630',
    projectId: 'noteworthy-79a91',
    storageBucket: 'noteworthy-79a91.appspot.com',
    iosClientId: '714095999630-lj7sot77b82gae4ab62ngtn6hpu18s9j.apps.googleusercontent.com',
    iosBundleId: 'ng.tiwachannels.noteworthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT-tpw618a08X6lJZvha19J2kbLUMx-HE',
    appId: '1:714095999630:ios:0e108b3a2d07e4e6b427df',
    messagingSenderId: '714095999630',
    projectId: 'noteworthy-79a91',
    storageBucket: 'noteworthy-79a91.appspot.com',
    iosClientId: '714095999630-hru68fvu1b7gtfeto00p73nj5o2euuco.apps.googleusercontent.com',
    iosBundleId: 'ng.tiwachannels.noteworthy.RunnerTests',
  );
}
